### ISSUE TITLE
Unable to add condition

### ISSUE THREAD

**Issue by Atrit** [jgm/highlighting-kate#101]
Hi ,
I want to add validation on username or password if it is entered or not.If not just display message.Below is my code,can you please help him .
On button click ,I am calling ClickButton

update Clickbutton state =
  onlyEffects state $ [ do  {authReq: authReq, key: key} <- addKey req
                            resp <- run (API call) state.runner
                            case resp of
                                 Nothing ->
                                   pure NoOp -- todo: display error
                                 (Just {status: StatusCode 200, response: S r}) ->
                                   pure $ PinPrompt {key: key, response: S r}
                                 (Just { response: E (Error {id: Just id, message: Just message})}) ->
                                   pure $ SetError message
                                 _ -> pure NoOp -- todo: display error
                      ]
    where req = { label: "xxx"
                , auth: Right {username: Username state.login, password: state.password}
                , parse_id: Nothing
                }
Thanks

**Comment by jgm** [comment]
This has nothing to do with this repo.
