### ISSUE TITLE
Extracting language data from languages

### ISSUE THREAD

**Issue by cryptonomicon314** [jgm/highlighting-kate#58]
Is it possible to extract data from languages, such as comment delimiters and keywords?

I'd like to be able to extract the pairs `(CommentTok, comment)` from a file and remove the leading (or trailing) comment delimiters from `comment`. Is it possible without parsing the XML files myself?

**Comment by jgm** [comment]
Sure, this is easy.

    highlightAs lang source

will produce a list of SourceLines.  A SourceLine is a list of Tokens.

So you just need to write a function

    extractComments :: [SourceLine] -> [String]

which might be

    extractComments = concatMap extractCommentsLine

    extractCommentsLine :: [Token] -> [Token]
    extractCommentsLine [] = []
    extractCommentsLine ((CommentTok, comment) : xs) =
      comment : extractCommentsLine xs
    extractCommentsLine (_:xs) = extractCommentsLine xs

This will give you a list of Strings.  Removing leading and trailing
delimiters from these should be straightforward.

+++ cryptonomicon314 [Jan 31 15 04:53 ]:

**Comment by cryptonomicon314** [comment]
I'm sorry if I haven't made myself clear. I am able to extract comments from the source code (which is, as you've shown, very easy). I was asking if there is a function that allows me to get the delimiters for each language. Something like this ``delimitersFor "haskell" === "--"`` or ``delimitersFor "python" === "#"`` (the same for multiline comments). I can obviously hardcode the delimiters in my code, but that would be a waste if I could get them directly from the package. I was just being extra lazy and trying to see if I could get the right delimiters from your library. From the inspection of the source code, it seems to be impossible, but I wanted to be sure.

Also, your function has a mistake which I also made the first time: you are assuming that a line that contains "only" a comment starts with ``(CommentTok, comment)``, but if the comment is indented, it will be start with ``(NormalTok, " ")``, and that line should obviously count as a "comment line" for any purpose.

**Comment by jgm** [comment]
+++ cryptonomicon314 [Jan 31 15 11:49 ]:
>I'm sorry if I haven't made myself clear. I am able to extract comments from the source code (which is, as you've shown, very easy). I was asking if there is a function that allows me to get the delimiters for each language. Something like this ``delimitersFor "haskell" === "--"`` or ``delimitersFor "python" === "#"`` (the same for multiline comments). I can obviously hardcode the delimiters in my code, but that would be a waste if I could get them directly from the package. I was just being extra lazy and trying to see if I could get the right delimiters from your library. From the inspection of the source code, it seems to be impossible, but I wanted to be sure.

Sorry, no.

>Also, your function has a mistake which I also made the first time: you are assuming that a line that contains "only" a comment starts with ``(CommentTok, comment)``, but if the comment is indented, it will be start with ``(NormalTok, " ")``, and that line should obviously count as a "comment line" for any purpose.

Hm, I don't think I assume that a line starts with a comment.  If it starts with NormalTok, then the (_:xs) clause will be invoked and we'll run the function again on the remainder, right?  Anyway, no matter, it's easy to write the function.

**Comment by cryptonomicon314** [comment]
Sorry, you're right, you're not assuming anything.

Anyway, your library is great and the idea of generating haskell modules at build time to recycle someone else's job is always something to praise in the laziest haskell style.
Thanks for your effort on this.

**Comment by jgm** [comment]
Can this be closed?

**Comment by cryptonomicon314** [comment]
Yes. I am now extracting data from the xml files directly.

**Comment by jgm** [comment]
I've been working on a new library, jgm/skylighting, which allows you to load xml definitions dynamically.
