### ISSUE TITLE
Build with regex-pcre?

### ISSUE THREAD

**Issue by felixonmars** [jgm/highlighting-kate#84]
I tried to understand why `regex-pcre-builtin` was used instead of `regex-pcre`, but didn't find an answer. I have tried to build highlighting-kate with the latest `regex-pcre` and succeeded. Is there any limitation on the `regex-pcre` module, or could there be a flag to use it?

Thanks!

**Comment by jgm** [comment]
+++ Felix Yan [Jan 25 16 02:03 ]:
>   I tried to understand why regex-pcre-builtin was used instead of
>   regex-pcre, but didn't find an answer. I have tried to build
>   highlighting-kate with the latest regex-pcre and succeeded. Is there
>   any limitation on the regex-pcre module, or could there be a flag to
>   use it?

I wanted a package that included the necessary C sources,
so people wouldn't have to install the C library pcre
separately.

**Comment by felixonmars** [comment]
I see, thank you. If the compatibility will always be maintained, would you accept a PR to add a flag to use `regex-pcre` and disabled by default? I think this will be better than downstream patches for distros :)

**Comment by jgm** [comment]
I think there's already a flag to use pcre-light, correct?

+++ Felix Yan [Jan 25 16 17:18 ]:

**Comment by felixonmars** [comment]
There is, but I am not sure if there is any functionality or performance difference between them. I can definitely use that if it's the same :)

**Comment by felixonmars** [comment]
Closing as I have enabled pcre-light in highlighting-kate-0.6.2 for the Arch package.
