### ISSUE TITLE
Specifying a new highlight definition at runtime?

### ISSUE THREAD

**Issue by rampion** [jgm/highlighting-kate#88]
If I have an XML file containing a new [Highlight Definition](https://docs.kde.org/stable5/en/applications/katepart/highlight.html#katehighlight-xml-format), do I need to convert it to haskell and recompile `highlighting-kate` to use it, or is there a mechanism which I can use to specify it at runtime? A parser which produces parsers?

**Comment by jgm** [comment]
Yes, you need to produce a Haskell module and recompile.

+++ Noah Luck Easterly [May 23 16 13:07 ]:
