### ISSUE TITLE
Haskell type identifier with non-ascii characters

### ISSUE THREAD

**Issue by conal** [jgm/highlighting-kate#92]
highlighting-kate 0.6.2.1 chops up Haskell type identifiers that contain non-ascii unicode characters, spoiling syntax coloring. (GHC Haskell 8 is happy with these identifiers.) Example:

    bash-3.2$ echo 'X₂Y' | highlighting-kate -s haskell | tail -1
    </style></head><body><div class="sourceCode"><pre class="sourceCode"><code class="sourceCode"><span class="dt">X</span>₂<span class="dt">Y</span></code></pre></div></body>
    bash-3.2$ highlighting-kate --version
    highlighting-kate 0.6.2.1 - (c) 2008 John MacFarlane

For lower-case identifiers, the identifier does not get split:

    bash-3.2$ echo 'x₂y' | highlighting-kate -s haskell | tail -1
    </style></head><body><div class="sourceCode"><pre class="sourceCode"><code class="sourceCode">x₂y</code></pre></div></body>

**Comment by jgm** [comment]
What's needed is an update to xml/haskell.xml, the kate
syntax definition file.  It only has ascii symbols for
operators.  If this is updated (and maybe there's already
an update in the kate repository?), we can easily regenerate
the parsers.

+++ Conal Elliott [Sep 16 16 13:06 ]:

**Comment by conal** [comment]
Sure enough. The kate repository's has haskell.xml version 4, while highlighting-kate has version 2.4. As an experiment, I copied the new haskell.xml and tried to rebuild, but I get a compilation error:

```

bash-3.2$ make prep
rm -rf Text/Highlighting/Kate/Syntax/*
stack install --install-ghc hxt regex-posix
regex-base-0.93.2: using precompiled package
network-uri-2.6.1.0: download
HUnit-1.3.1.1: download
regex-posix-0.95.2: download
hxt-charproperties-9.2.0.1: download
network-uri-2.6.1.0: configure
network-uri-2.6.1.0: build
HUnit-1.3.1.1: configure
HUnit-1.3.1.1: build
regex-posix-0.95.2: configure
regex-posix-0.95.2: build
hxt-charproperties-9.2.0.1: configure
hxt-charproperties-9.2.0.1: build
HUnit-1.3.1.1: copy/register
network-uri-2.6.1.0: copy/register
regex-posix-0.95.2: copy/register
hxt-charproperties-9.2.0.1: copy/register
hxt-regex-xmlschema-9.2.0.2: download
hxt-unicode-9.0.2.4: download
hxt-unicode-9.0.2.4: configure
hxt-unicode-9.0.2.4: build
hxt-regex-xmlschema-9.2.0.2: configure
hxt-regex-xmlschema-9.2.0.2: build
hxt-unicode-9.0.2.4: copy/register
hxt-regex-xmlschema-9.2.0.2: copy/register
hxt-9.3.1.15: download
hxt-9.3.1.15: configure
hxt-9.3.1.15: build
hxt-9.3.1.15: copy/register
Completed 8 action(s).
stack runghc ./ParseSyntaxFiles.hs xml

ParseSyntaxFiles.hs:35:1: error:
    Failed to load interface for ‘Data.ByteString.UTF8’
    Perhaps you meant
      Data.ByteString.Char8 (from bytestring-0.10.8.1)
      Data.ByteString.Lazy (from bytestring-0.10.8.1)
      Data.String.UTF8 (from hxt-unicode-9.0.2.4)
    Use -v to see a list of the files searched for.
make: *** [prep] Error 1
bash-3.2$ 
```

**Comment by jgm** [comment]
Fixed in 0.6.3.

**Comment by conal** [comment]
Hm. I'm seeing the same behavior in 0.6.3:

```
bash-3.2$ echo 'X₂Y' | highlighting-kate -s haskell | tail -1
</style></head><body><div class="sourceCode"><pre class="sourceCode"><code class="sourceCode"><span class="dt">X</span>₂<span class="dt">Y</span></code></pre></div></body>
bash-3.2$ highlighting-kate --version
highlighting-kate 0.6.3 - (c) 2008 John MacFarlane
bash-3.2$ 
```

**Comment by jgm** [comment]
Tell me what output you're expecting here.
Is it that you want the little 2 to be highlighted as an
operator?  I'm afraid the kate xml file doesn't currently
allow for that.

+++ Conal Elliott [Sep 18 16 12:49 ]:

**Comment by conal** [comment]
I'm looking for type identifiers to be treated as GHC Haskell does, which can include the numeric subscript unicode characters. I don't know exactly which unicode characters are allowed in identifiers, nor how to specify unicode character ranges in the regexps that highlighting-kate uses.

My motivation: I was hoping to pretty up my Haskell identifiers in a Pandoc filter by replacing numeric suffixes with corresponding unicode subscripted versions of the digits. However, the syntax coloring breaks when the identifiers get divided up. Even without the coloring issue, however, the result doesn't look great.

Maybe I'd be better off doing an HTML transformation, where I can use HTML subscripting. In that case, the unicode highlighting-kate issue won't arise.
